import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

public class TransshipmentEngine {

    // Supply Chain Cost Constants
    private static final double ANNUAL_HOLDING_COST_PCT = 0.20;
    private static final double PROFIT_MARGIN_PCT = 0.30;
    private static final double BASE_FREIGHT_COST = 50.0;
    private static final double RATE_PER_MILE = 0.15;
    private static final double HANDLING_FEE = 20.0;
    private static final int ORIGIN_SAFETY_STOCK_BUFFER = 10; 

    public static void main(String[] args) {
        System.out.println("Initializing Logistics Decision Engine...");
        System.out.println("Ingesting Mock Dataset...\n");
        
        // Define the path to the CSV file generated by your Python script
        String csvFile = "mock_logistics_data.csv";
        processLogisticsData(csvFile);
    }

    public static void processLogisticsData(String filePath) {
        String line = "";
        String cvsSplitBy = ",";
        int totalEvaluated = 0;
        int totalTransfers = 0;
        double totalNetworkSavings = 0.0;

        try (BufferedReader br = new BufferedReader(new FileReader(filePath))) {
            // Read and skip the header row
            br.readLine();

            while ((line = br.readLine()) != null) {
                // Split the row by commas
                String[] data = line.split(cvsSplitBy);

                // Parse columns based on the Python script output structure
                String date = data[0];
                String sku = data[1];
                double unitCost = Double.parseDouble(data[2]);
                String originNode = data[3];
                String destNode = data[4];
                double distanceMiles = Double.parseDouble(data[5]);
                int originOnHand = Integer.parseInt(data[6]);
                int destOnHand = Integer.parseInt(data[7]);
                int destDailyDemand = Integer.parseInt(data[8]);
                int daysStagnant = Integer.parseInt(data[9]);
                int leadTimeDays = Integer.parseInt(data[10]);

                // Run the core decision algorithm
                DecisionResult result = evaluateTransfer(sku, unitCost, distanceMiles, originOnHand, 
                                                         destOnHand, destDailyDemand, daysStagnant, leadTimeDays);
                
                totalEvaluated++;
                
                // Print only the approved transfers to keep the terminal output clean
                if (result.isApproved) {
                    totalTransfers++;
                    totalNetworkSavings += result.netSavings;
                    System.out.printf("[APPROVED] %s: Move %d units from %s to %s | Network Savings: $%.2f\n", 
                        sku, result.transferQuantity, originNode, destNode, result.netSavings);
                }
            }
            
            // Print the final simulation summary
            System.out.println("\n=== BATCH PROCESSING COMPLETE ===");
            System.out.println("Total Routes Evaluated: " + totalEvaluated);
            System.out.println("Total Transfers Approved: " + totalTransfers);
            System.out.printf("Total Network Savings: $%.2f\n", totalNetworkSavings);

        } catch (IOException e) {
            System.err.println("Error reading CSV file. Ensure 'mock_logistics_data.csv' is in the same directory.");
            System.err.println("Error details: " + e.getMessage());
        }
    }

    public static DecisionResult evaluateTransfer(String sku, double unitCost, double distanceMiles, 
                                        int originOnHand, int destOnHand, int destDailyDemand, 
                                        int daysStagnant, int leadTimeDays) {
        
        DecisionResult result = new DecisionResult();

        // 1. Calculate Financial Tipping Point
        double accumulatedHoldingCost = (unitCost * ANNUAL_HOLDING_COST_PCT) * (daysStagnant / 365.0);
        double costOfLostSale = unitCost * PROFIT_MARGIN_PCT;
        double totalCostOfInaction = accumulatedHoldingCost + costOfLostSale;
        double totalFreightCost = BASE_FREIGHT_COST + (distanceMiles * RATE_PER_MILE) + HANDLING_FEE;

        boolean isFinanciallyViable = totalCostOfInaction > totalFreightCost;

        // 2. Calculate Inventory Constraints and Triggers
        double reorderPoint = (destDailyDemand * leadTimeDays) * 1.2; // Includes 20% safety stock buffer
        boolean isStockoutImminent = destOnHand <= reorderPoint;

        int originSurplus = originOnHand - ORIGIN_SAFETY_STOCK_BUFFER;
        int destDeficit = (int) Math.ceil(reorderPoint - destOnHand);
        int transferQuantity = Math.min(originSurplus, destDeficit);

        // 3. Final Decision Logic
        if (isFinanciallyViable && isStockoutImminent && transferQuantity > 0) {
            result.isApproved = true;
            result.transferQuantity = transferQuantity;
            result.netSavings = totalCostOfInaction - totalFreightCost;
        } else {
            result.isApproved = false;
            if (!isFinanciallyViable) {
                result.rejectReason = "Freight cost exceeds inaction penalty.";
            } else if (!isStockoutImminent) {
                result.rejectReason = "Destination inventory remains above Reorder Point.";
            } else {
                result.rejectReason = "Insufficient surplus at Origin node.";
            }
        }
        return result;
    }

    // Inner class to structure the output data nicely
    public static class DecisionResult {
        public boolean isApproved;
        public int transferQuantity;
        public double netSavings;
        public String rejectReason;
    }
}
